import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.scss";
import vars from '@/styles/variables.module.scss';
import styles from './_style/layout.module.scss'

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Aries",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const url = 'https://baidu.com'; // 点击 twitter 卡片时跳转的地址
    const image = 'http://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/6c85f43aed61e320ebec194e6a78d6d3.png~tplv-uwbnlip3yd-png.png'; // 卡片识别到的图片地址
    return (
        <html lang="en">
        <body className={styles.body}>{children}</body>
        <meta name="twitter:site" content="@xxx"/>
        <meta name="twitter:creator" content="@xxx"/>
        <meta property="og:url" content={url}/>
        <meta property="og:title" content="memescan:title"/>
        <meta property="og:image" content={image}/>
        <meta content="summary_large_image" name="twitter:card"/>
        </html>
    );
}
