/* tslint:disable */
/* eslint-disable */
/**
 * aries/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AriesPingResponse,
  RpcStatus,
} from '../models/index';
import {
    AriesPingResponseFromJSON,
    AriesPingResponseToJSON,
    RpcStatusFromJSON,
    RpcStatusToJSON,
} from '../models/index';

export interface AriesServicePingRequest {
    text?: string;
}

/**
 * 
 */
export class AriesServiceApi extends runtime.BaseAPI {

    /**
     */
    async ariesServicePingRaw(requestParameters: AriesServicePingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AriesPingResponse>> {
        const queryParameters: any = {};

        if (requestParameters['text'] != null) {
            queryParameters['text'] = requestParameters['text'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/ping`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AriesPingResponseFromJSON(jsonValue));
    }

    /**
     */
    async ariesServicePing(requestParameters: AriesServicePingRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AriesPingResponse> {
        const response = await this.ariesServicePingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
