/* tslint:disable */
/* eslint-disable */
/**
 * aries/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AriesPingResponse
 */
export interface AriesPingResponse {
    /**
     * 
     * @type {string}
     * @memberof AriesPingResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the AriesPingResponse interface.
 */
export function instanceOfAriesPingResponse(value: object): value is AriesPingResponse {
    return true;
}

export function AriesPingResponseFromJSON(json: any): AriesPingResponse {
    return AriesPingResponseFromJSONTyped(json, false);
}

export function AriesPingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AriesPingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AriesPingResponseToJSON(value?: AriesPingResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

